# Generated by Django 4.0.3 on 2022-04-11 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('teamA', models.CharField(max_length=255)),
                ('teamA_image', models.ImageField(upload_to='')),
                ('teamB', models.CharField(max_length=255)),
                ('teamB_image', models.ImageField(upload_to='')),
                ('start_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resultA', models.IntegerField()),
                ('resultB', models.IntegerField()),
                ('who_score_first', models.CharField(choices=[('TeamA', 'TeamA'), ('TeamB', 'TeamB'), ('NoTeam', 'NoTeam')], default='NoTeam', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicts.matchpredict')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
