# Generated by Django 4.0.3 on 2022-04-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
