# Generated by Django 4.0.3 on 2022-04-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('player_image', models.ImageField(upload_to='')),
                ('from_team', models.CharField(max_length=255)),
                ('to_team', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('transfer_date', models.DateTimeField()),
            ],
        ),
    ]
