# Generated by Django 4.0.3 on 2022-04-11 03:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tourName', models.CharField(max_length=255)),
                ('teamA', models.CharField(max_length=255)),
                ('teamA_image', models.ImageField(upload_to='')),
                ('resultA', models.IntegerField()),
                ('teamB', models.CharField(max_length=255)),
                ('teamB_image', models.ImageField(upload_to='')),
                ('resultB', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('stream_url', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
