# Generated by Django 4.0.3 on 2022-04-18 19:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='descreption',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='stream_url',
            field=models.URLField(),
        ),
    ]
