# Generated by Django 4.0.4 on 2022-04-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_descreption_alter_match_stream_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teamA_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='teamB_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
