# Generated by Django 4.0.3 on 2022-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_match_teama_image_alter_match_teamb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_file',
            field=models.FileField(default=None, null=True, upload_to='media/match files'),
        ),
    ]
