# Generated by Django 4.0.3 on 2022-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_match_match_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_file',
        ),
        migrations.AddField(
            model_name='match',
            name='stream_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/match files'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stream_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
