# Generated by Django 4.0.3 on 2022-05-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_remove_match_match_file_match_stream_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='stream_file',
        ),
        migrations.AlterField(
            model_name='match',
            name='stream_url',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
